<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "viewModel": {
                        "component": "VendorAxel_ModuleKnockoutJsAndSimpleJsViewModels/js/example30-es5-observables-with-ko-track",
                        "base_url": "<?= $block->escapeJs($block->getBaseUrl())?>"
                    }
                }
            }
        }
    }
</script>
<div data-bind="scope: 'viewModel'">
    <h3 data-bind="text: label"></h3>
    <table data-bind="foreach: items">
        <tr>
            <td data-bind="text: name"></td>
            <td data-bind="text: qty"></td>
            <td data-bind="text: price"></td>
            <td data-bind="text: $parent.rowTotal($data)"></td>
        </tr>
    </table>
    <div>Additional Charge: <span data-bind="text: additional_charge"></span></div>
    <strong>Total: <span data-bind="text: total()"></span></strong>
</div>
