<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "viewModel": {
                        "component": "VendorAxel_ModuleKnockoutJsAndSimpleJsViewModels/js/example27-ko-computed-observable",
                        "base_url": "<?= $block->escapeJs($block->getBaseUrl())?>"
                    }
                }
            }
        }
    }
</script>
<div data-bind="scope: 'viewModel'">
    <h2 data-bind="text: output"></h2>
</div>