<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "viewModel": {
                        "component": "VendorAxel_ModuleKnockoutJsAndSimpleJsViewModels/js/example23-debugging-ko-viewmodels-with-uiregistry"
                    }
                }
            }
        }
    }
</script>
<!--Magento_Ui/js/core/app = This app instance is assigned a list "components" (this config will be merged)-->
<!--viewModel22 = is the name of the component (a declaration of a component)-->


<!--bind this section (this div) to a view model (everything inside is bound with the component "viewModel22")-->
<div data-bind="scope: 'viewModel'">
    <h2 data-bind="text: title"></h2>
</div>
<!--because title doesn't have quotes, it referres to a property of the view model-->