<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "viewModel": {
                        "component": "VendorAxel_ModuleKnockoutJsAndSimpleJsViewModels/js/example29-ko-virtual-elements",
                        "base_url": "<?= $block->escapeJs($block->getBaseUrl())?>"
                    }
                }
            }
        }
    }
</script>
<div data-bind="scope: 'viewModel'">
    <table>
        <tr>
            <th data-bind="i18n: 'Currency to'"></th>
            <th data-bind="i18n: 'Rate'"></th>
        </tr>
        <!-- ko foreach: exchange_rates -->
        <tr>
            <td data-bind="text: currency_to"></td>
            <td data-bind="text: rate"></td>
        </tr>
        <!-- /ko -->
    </table>
</div>