<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

?>
<!--Video: https://www.mage2.tv/content/javascript/jquery-ui-widgets/instantiating-jquery-ui-widgets-e.g.-javascript-form-validation/-->
<!--Video description:-->
<!--Much of the Magento frontend functionality is built using jQuery UI widgets.-->
<!--This video discusses how to create a widget instance using the form validation widget as an example.-->
<!------->


<div>adding module</div>