<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

?>
<!--<script type="text/x-magento-init">-->
<!--    {-->
<!--        "div#target": {-->
<!--            "VendorAxel_ModuleJs/js/script-example6-requirejs": {-->
<!--                "base_url": " $block->escapeJs($block->getBaseUrl())"-->
<!--            }-->
<!--        }-->
<!--    }-->
<!--</script>-->

<!--when targetting a specific dom-node, you also can use a different approach: using the "data-mage-init" attribute-->
<!--because this is written in json, you need to use single quotes-->
<!--copy the configuration from above into the data-mage-init (this dic is the selector)-->
<div id="target" data-mage-init='{
        "VendorAxel_ModuleJs/js/script-example6-requirejs": {
            "base_url": "<?= $block->escapeJs($block->getBaseUrl()) ?>"
        }
    }'>
    put js on this dom node
</div>