<!--
Video: https://www.mage2.tv/content/javascript/jquery-ui-widgets/loading-the-content-for-a-collapsible-jquery-ui-widget-via-ajax/
Video description:
The content of a collapsible widget can be loaded on demand via Ajax.
-->

<!--We need a config option "ajaxContent":true and-->
<!--We need a href in the data-mage-init-container-->

<div id="my-collapsible-container-id" data-mage-init='{"collapsible": {"ajaxContent": true}}'>
    <div data-role="title">
        <h2>This is a collapsible widget</h2>
        <button data-role="trigger">click</button>
    </div>
    <div id="example20-content" data-role="content"></div>
    <a href="<?= $block->getViewFileUrl('VendorAxel_ModuleJqueryUiWidgets/example20-loading-content-for-a-jquery-ui-widget-via-ajax.html')?>" data-ajax="true"></a>
</div>