<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

?>

<script type="text/x-magento-init">
    {
        "div#target": {
            "VendorAxel_ModuleRequireJsAndMagentoFundamentals/js/example5-targetting-dom-nodes": {
                "base_url": "<?= $block->escapeJs($block->getBaseUrl()) ?>"
            }
        }
    }
</script>
<div id="target">put js on this dom node</div>