<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

?>

<script type="text/x-magento-init">
    {
        "*": {
            "VendorAxel_ModuleRequireJsAndMagentoFundamentals/js/example4-passing-arguments-from-php-to-js": {
                "base_url": "<?= $block->escapeJs($block->getBaseUrl()) ?>"
            }
        }
    }
</script>
<!--pass some php variables into the object of the javascript-key "VendorAxel_ModuleRequireJsAndMagentoFundamentals/js/script-example3-requirejs"-->
