<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "viewModel": {
                        "component": "VendorAxel_MagentoUiComponents/js/example32-Js-uicomponent-class-hierarchy"
                    }
                }
            }
        }
    }
</script>