<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "myUiComponent": {
                        "component": "VendorAxel_MagentoUiComponents/js/example32-js-uicomponent-class-hierarchy"
                    }
                }
            }
        }
    }
</script>
<div data-bind="scope: 'myUiComponent'">
    <div data-bind="text: label"></div>
</div>
