<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "myUiComponent": {
                        "component": "VendorAxel_MagentoUiComponents/js/example33-js-uicomponent-defaults-configuration",
                        "label": "JSON label property (lvl 3)",
                        "config": {
                          "label" : "JSON config.label property (lvl 4)"
                        }
                    }
                }
            }
        }
    }
</script>
<div data-bind="scope: 'myUiComponent'">
    <div data-bind="text: label"></div>
</div>
