<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "myUiComponent": {
                        "component": "VendorAxel_MagentoUiComponents/js/example34-uicomponent-ko-templates"
                    }
                }
            }
        }
    }
</script>
<div data-bind="scope: 'myUiComponent'">
<!-- specify that we want to render a template -->
<!-- ko template: getTemplate() --><!-- /ko -->
</div>
