<!--
Video:
https://www.mage2.tv/content/javascript/jquery-ui-widgets/introduction-to-the-collapsible-jquery-ui-widget/
Video description:
This video introduces the collapsible jQuery UI Widget Magento provides.
-->

<div data-mage-init='{"collapsible":{}}'>
    <div data-role="title">
        <h2>This is a collapsible widget</h2>
    </div>
    <div data-role="content" style="display: none">
        <p>This is my content</p>
    </div>
</div>
