<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

?>

<!--
Video:
https://www.mage2.tv/content/javascript/jquery-ui-widgets/instantiating-jquery-ui-widgets-e.g.-javascript-form-validation/
Video description:
Much of the Magento frontend functionality is built using jQuery UI widgets.
This video discusses how to create a widget instance using the form validation widget as an example.
-->

<form data-mage-init='{"validation":{}}'>
    <div class="control">
        <input type="text" name="email" id="email" class="input-text"
            placeholder="<?= __('Your email') ?>"
            data-validate="{required: true,'validate-email': true}" />
    </div>
    <button type="submit" class="action primary"><?= __('Submit') ?></button>
</form>

<!--
validation is an alias for mage/validation/validation
search validation with fileMask "*config.js"
src/vendor/magento/module-theme/view/frontend/requirejs-config.js:29

data-validate rules can be found:
search validate-email with fileMask "*.js"
src/vendor/magento/module-ui/view/base/web/js/lib/validation/rules.js:442
-->
