<!--
Video:
https://www.mage2.tv/content/javascript/jquery-ui-widgets/make-a-collapsible-jquery-ui-widget-open-by-default/
Video description:
Collapsible widgets can be open by default,
either by specifying the content ID as an URL fragment,
or by providing the "active" option to the widget configuration.
-->

<!--
Example 1 - with a fragment in the url
we added an id so we can use a fragment in the url: http://axel.local/#example
-->
<!--<div data-mage-init='{"collapsible":{}}'>-->
<!--    <div data-role="title">-->
<!--        <h2>This is a collapsible widget</h2>-->
<!--        <button data-role="trigger">click</button>-->
<!--    </div>-->
<!--    <div id="example" data-role="content">-->
<!--        <p>This is my content</p>-->
<!--    </div>-->
<!--</div>-->


<!--
Example 2 - use the active/true config
-->
<div data-mage-init='{"collapsible":{"active":true}}'>
    <div data-role="title">
        <h2>This is a collapsible widget</h2>
        <button data-role="trigger">click</button>
    </div>
    <div data-role="content">
        <p>This is my content</p>
    </div>
</div>
