<!--
Video:
https://www.mage2.tv/content/javascript/jquery-ui-widgets/adding-a-trigger-element-to-a-collapsible-jquery-ui-widget/
Video description:
This video shows how to specify a trigger element to open or hide the collapsible widget content.
-->

<div data-mage-init='{"collapsible":{}}'>
    <div data-role="title">
        <h2>This is a collapsible widget</h2>
        <button data-role="trigger">click</button>
    </div>
    <div data-role="content" style="display: none">
        <p>This is my content</p>
    </div>
</div>
